sudo: required
services:
  - docker

before_install:
  - docker build -t sithu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sithu/docker-react npm run test -- --coverage

after_success:
  - docker build -t sithu/docker-react .
